import Anthropic from '@anthropic-ai/sdk';
import { getServerEnv } from '@/lib/env';
import { getPresetById } from '@/lib/stylePresets';
import type { GeneratePromptRequest, GeneratePromptResponse } from '@/types/api';

// System prompt for Claude - defines the rules for generating image prompts
const SYSTEM_PROMPT = `You are an expert prompt engineer for AI image generation models.

Your task is to transform a user's idea into a detailed, effective prompt for generating images.

CRITICAL RULES - NEVER VIOLATE THESE:
1. Never describe transparent backgrounds, checkered patterns, or alpha channels
2. Never describe UI elements: frames, borders, crop handles, screenshot elements, buttons, windows
3. Never include watermarks, logos, or text in the image unless explicitly requested by the user
4. For "space for text" or "text area" requests, describe real negative space or low-complexity areas in the scene composition:
   - Examples: "expansive sky area", "large empty wall section", "calm uncluttered region", "plenty of breathing room on the left side", "simple gradient background area"
   - NEVER describe artificial blur effects or hard-edged out-of-focus regions - these look unnatural
   - Instead use: smooth gradients, solid color areas, simple textures, or naturally distant backgrounds with shallow depth of field
5. Focus on tangible, photographable or drawable scenes only

STRUCTURE YOUR PROMPTS TO INCLUDE:
- Subject and main action/pose
- Setting and environment details
- Lighting conditions and mood
- Color palette and tones
- Camera angle/perspective (for photos) or art style (for illustrations)
- Specific stylistic elements from the selected preset

OUTPUT FORMAT:
Provide a single, cohesive prompt paragraph. Do not include explanations, bullet points, or metadata.
The prompt should be 2-4 sentences, detailed but focused.`;

// Get mock response for development
function getMockResponse(request: GeneratePromptRequest): GeneratePromptResponse {
  const preset = getPresetById(request.styleId);
  const presetStyle = preset?.promptDirectives || 'professional quality';
  
  const mockPrompts: Record<string, string> = {
    photo: `${request.userIdea}. ${presetStyle}. Shot with natural lighting, soft shadows, and a shallow depth of field creating beautiful bokeh in the background. The composition leaves ample negative space for text placement.`,
    illustration: `${request.userIdea}. ${presetStyle}. Clean and modern aesthetic with balanced composition and harmonious color palette. The layout includes generous negative space suitable for overlay text.`,
  };

  return {
    prompt: mockPrompts[request.mode] || mockPrompts.photo,
    reasoning: 'Mock response generated for development',
  };
}

// Generate prompt using Claude
export async function generatePrompt(request: GeneratePromptRequest): Promise<GeneratePromptResponse> {
  // Check for mock mode or missing API key
  const isMockMode = process.env.NEXT_PUBLIC_MOCK_AI === 'true' || !process.env.ANTHROPIC_API_KEY;
  
  if (isMockMode) {
    // Simulate API delay
    await new Promise((r) => setTimeout(r, 1000));
    return getMockResponse(request);
  }

  const env = getServerEnv();
  const client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });

  const preset = getPresetById(request.styleId);
  const presetInfo = preset
    ? `Selected style: "${preset.label}" - ${preset.promptDirectives}. Layout hints: ${preset.layoutHints}`
    : '';

  const userMessage = `Create an image generation prompt for this idea:

User's idea: ${request.userIdea}

Mode: ${request.mode === 'photo' ? 'Photorealistic photography' : 'Digital illustration'}
Aspect ratio: ${request.aspectRatio || '1:1'}
${presetInfo}

Generate a detailed prompt that captures this vision while following all the rules.`;

  const response = await client.messages.create({
    model: 'claude-sonnet-4-5-20250929',
    max_tokens: 500,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: userMessage,
      },
    ],
  });

  // Extract text from response
  const textContent = response.content.find((block) => block.type === 'text');
  const prompt = textContent?.type === 'text' ? textContent.text : '';

  return {
    prompt: prompt.trim(),
    reasoning: 'Generated by Claude',
  };
}

