import { getServerEnv } from '@/lib/env';
import type { GenerateImageRequest, GenerateImageResponse, GeneratedImage } from '@/types/api';

// Placeholder image URLs for mock mode
const MOCK_IMAGES = [
  'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1080&q=80',
  'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1080&q=80',
  'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=1080&q=80',
  'https://images.unsplash.com/photo-1557683316-973673baf926?w=1080&q=80',
];

// Get mock response for development
function getMockResponse(): GenerateImageResponse {
  const randomImage = MOCK_IMAGES[Math.floor(Math.random() * MOCK_IMAGES.length)];
  
  return {
    images: [
      {
        id: `mock_${Date.now()}`,
        url: randomImage,
        createdAt: new Date().toISOString(),
      },
    ],
  };
}

// Generate image using Google Imagen 3 API
export async function generateImage(request: GenerateImageRequest): Promise<GenerateImageResponse> {
  // Check for mock mode or missing API key
  const isMockMode = process.env.NEXT_PUBLIC_MOCK_AI === 'true' || !process.env.GOOGLE_API_KEY;
  
  if (isMockMode) {
    // Simulate API delay
    await new Promise((r) => setTimeout(r, 2000));
    return getMockResponse();
  }

  const env = getServerEnv();
  // Use gemini-3-pro-image-preview (same as working Laravel project)
  const model = 'gemini-3-pro-image-preview';
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${env.GOOGLE_API_KEY}`;

  // Build the prompt with style hints
  const styleHint = request.mode === 'illustration'
    ? 'Create as a digital illustration or artwork.'
    : 'Create as a photorealistic image.';

  // Add product positioning instructions if product image is provided
  const productPositioning = request.productImage
    ? '\n\nIMPORTANT: The provided product image should be prominently featured in the bottom-right area of the composition. Create a background that complements and enhances the product while keeping the product clearly visible.'
    : '';

  const fullPrompt = `${request.prompt}\n\n${styleHint}${productPositioning}`;

  // Map aspect ratio to API format (default to 1:1 if not specified)
  const aspectRatio = request.aspectRatio || '1:1';

  // Build parts array - text first, then optional product image
  const parts: Array<{ text: string } | { inline_data: { mime_type: string; data: string } }> = [
    { text: fullPrompt }
  ];

  // Add product image if provided (Image-to-Image mode)
  if (request.productImage) {
    parts.push({
      inline_data: {
        mime_type: request.productImage.mimeType,
        data: request.productImage.data,
      }
    });
  }

  try {
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts
          }
        ],
        generationConfig: {
          responseModalities: ['TEXT', 'IMAGE'],
          imageConfig: {
            aspectRatio: aspectRatio,
            imageSize: '2K',
          },
        },
      }),
      // Increase timeout to 120 seconds (same as Laravel project)
      signal: AbortSignal.timeout(120000),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Google Imagen API error:', response.status, errorText);
      throw new Error(`API request failed: ${response.status}`);
    }

    const result = await response.json();

    // Extract image from response
    const images: GeneratedImage[] = [];
    
    // Check candidates array
    if (result.candidates && result.candidates.length > 0) {
      const candidate = result.candidates[0];
      
      if (candidate.content && candidate.content.parts) {
        for (const part of candidate.content.parts) {
          // Check for inlineData with image
          if (part.inlineData && part.inlineData.mimeType && part.inlineData.mimeType.startsWith('image/')) {
            const base64Data = part.inlineData.data;
            const mimeType = part.inlineData.mimeType;
            const dataUrl = `data:${mimeType};base64,${base64Data}`;
            
            images.push({
              id: `gen_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`,
              url: dataUrl,
              createdAt: new Date().toISOString(),
            });
          }
        }
      }
    }

    if (images.length === 0) {
      console.warn('No image generated by Imagen 3, response:', JSON.stringify(result, null, 2));
      // Fall back to mock on error
      return getMockResponse();
    }

    return { images };
  } catch (error) {
    console.error('Imagen 3 image generation error:', error);
    // Fall back to mock on error
    return getMockResponse();
  }
}
